<?php

use Illuminate\Database\Seeder;

class RoomPricesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('room__prices')->insert(
                [
                    [
                        'per_hour' => 600,
                        'per_two' => NULL,
                        'per_three' => 1500,
                        'per_two_plus' => NULL,
                        'per_three_plus' => NULL,
                        'five_ticket' => 6000,
                        'ten_ticket' => NULL,
                        'daypart' => 1,
                    ],
                    [
                        'per_hour' => 650,
                        'per_two' => NULL,
                        'per_three' => 1600,
                        'per_two_plus' => NULL,
                        'per_three_plus' => NULL,
                        'five_ticket' => 6400,
                        'ten_ticket' => NULL,
                        'daypart' => 1,
                    ],  
                    [
                        'per_hour' => 700,
                        'per_two' => NULL,
                        'per_three' => 1700,
                        'per_two_plus' => NULL,
                        'per_three_plus' => NULL,
                        'five_ticket' => 6800,
                        'ten_ticket' => NULL,
                        'daypart' => 1,
                    ],  
                    [
                        'per_hour' => 750,
                        'per_two' => NULL,
                        'per_three' => 1800,
                        'per_two_plus' => NULL,
                        'per_three_plus' => NULL,
                        'five_ticket' => 7200,
                        'ten_ticket' => NULL,
                        'daypart' => 1,
                    ],  
                    [
                        'per_hour' => 800,
                        'per_two' => NULL,
                        'per_three' => 1900,
                        'per_two_plus' => NULL,
                        'per_three_plus' => NULL,
                        'five_ticket' => 7600,
                        'ten_ticket' => NULL,
                        'daypart' => 1,
                    ],  
                    [
                        'per_hour' => 900,
                        'per_two' => NULL,
                        'per_three' => 2500,
                        'per_two_plus' => NULL,
                        'per_three_plus' => NULL,
                        'five_ticket' => 10000,
                        'ten_ticket' => NULL,
                        'daypart' => 1,
                    ],  
                    [
                        'per_hour' => 950,
                        'per_two' => NULL,
                        'per_three' => 2600,
                        'per_two_plus' => NULL,
                        'per_three_plus' => NULL,
                        'five_ticket' => 10400,
                        'ten_ticket' => NULL,
                        'daypart' => 1,
                    ],  
                    [
                        'per_hour' => 1000,
                        'per_two' => NULL,
                        'per_three' => 2700,
                        'per_two_plus' => NULL,
                        'per_three_plus' => NULL,
                        'five_ticket' => 10800,
                        'ten_ticket' => NULL,
                        'daypart' => 1,
                    ],  
                    [
                        'per_hour' => 1050,
                        'per_two' => NULL,
                        'per_three' => 2800,
                        'per_two_plus' => NULL,
                        'per_three_plus' => NULL,
                        'five_ticket' => 11200,
                        'ten_ticket' => NULL,
                        'daypart' => 1,
                    ],  
                    [
                        'per_hour' => 1100,
                        'per_two' => NULL,
                        'per_three' => 2900,
                        'per_two_plus' => NULL,
                        'per_three_plus' => NULL,
                        'five_ticket' => 11600,
                        'ten_ticket' => NULL,
                        'daypart' => 1,
                    ],  
                    [
                        'per_hour' => 300,
                        'per_two' => NULL,
                        'per_three' => 700,
                        'per_two_plus' => NULL,
                        'per_three_plus' => NULL,
                        'five_ticket' => 2800,
                        'ten_ticket' => 2200,
                        'daypart' => 1,
                    ],  
                    [
                        'per_hour' => 600,
                        'per_two' => NULL,
                        'per_three' => 1400,
                        'per_two_plus' => NULL,
                        'per_three_plus' => NULL,
                        'five_ticket' => 5600,
                        'ten_ticket' => 4400,
                        'daypart' => 1,
                    ],  
                    [
                        'per_hour' => 1500,
                        'per_two' => NULL,
                        'per_three' => 4000,
                        'per_two_plus' => NULL,
                        'per_three_plus' => NULL,
                        'five_ticket' => 16000,
                        'ten_ticket' => NULL,
                        'daypart' => 1,
                    ],  
                    [
                        'per_hour' => 800,
                        'per_two' => NULL,
                        'per_three' => 2000,
                        'per_two_plus' => NULL,
                        'per_three_plus' => NULL,
                        'five_ticket' => 8000,
                        'ten_ticket' => NULL,
                        'daypart' => 1,
                    ],  
                    [
                        'per_hour' => 1200,
                        'per_two' => NULL,
                        'per_three' => 3000,
                        'per_two_plus' => NULL,
                        'per_three_plus' => NULL,
                        'five_ticket' => 12000,
                        'ten_ticket' => NULL,
                        'daypart' => 1,
                    ],  
                    [
                        'per_hour' => 1000,
                        'per_two' => NULL,
                        'per_three' => NULL,
                        'per_two_plus' => NULL,
                        'per_three_plus' => NULL,
                        'five_ticket' => NULL,
                        'ten_ticket' => NULL,
                        'daypart' => 1,
                    ],  
                    [
                        'per_hour' => 1050,
                        'per_two' => 1600,
                        'per_three' => 2400,
                        'per_two_plus' => 7040,
                        'per_three_plus' => 10560,
                        'five_ticket' => 6400,
                        'ten_ticket' => NULL,
                        'daypart' => 0,
                    ],
                    [
                        'per_hour' => 1060,
                        'per_two' => 1680,
                        'per_three' => 2525,
                        'per_two_plus' => 7392,
                        'per_three_plus' => 11110,
                        'five_ticket' => 6720,
                        'ten_ticket' => NULL,
                        'daypart' => 0,
                    ],  
                    [
                        'per_hour' => 1300,
                        'per_two' => 2180,
                        'per_three' => 3275,
                        'per_two_plus' => 9592,
                        'per_three_plus' => 14410,
                        'five_ticket' => 8720,
                        'ten_ticket' => NULL,
                        'daypart' => 0,
                    ],  
                    [
                        'per_hour' => 1450,
                        'per_two' => 2480,
                        'per_three' => 3725,
                        'per_two_plus' => 10912,
                        'per_three_plus' => 16390,
                        'five_ticket' => 9920,
                        'ten_ticket' => NULL,
                        'daypart' => 0,
                    ],  
                    [
                        'per_hour' => 1600,
                        'per_two' => 2650,
                        'per_three' => 3975,
                        'per_two_plus' => 11660,
                        'per_three_plus' => 17490,
                        'five_ticket' => 10600,
                        'ten_ticket' => NULL,
                        'daypart' => 0,
                    ],  
                    [
                        'per_hour' => 1280,
                        'per_two' => 2170,
                        'per_three' => 3250,
                        'per_two_plus' => 9548,
                        'per_three_plus' => 14300,
                        'five_ticket' => 8680,
                        'ten_ticket' => NULL,
                        'daypart' => 0,
                    ],  
                    [
                        'per_hour' => 1350,
                        'per_two' => 2230,
                        'per_three' => 3350,
                        'per_two_plus' => 9812,
                        'per_three_plus' => 14740,
                        'five_ticket' => 8920,
                        'ten_ticket' => NULL,
                        'daypart' => 0,
                    ],  
                    [
                        'per_hour' => 1400,
                        'per_two' => 2400,
                        'per_three' => 3600,
                        'per_two_plus' => 10560,
                        'per_three_plus' => 15840,
                        'five_ticket' => 9600,
                        'ten_ticket' => NULL,
                        'daypart' => 0,
                    ],  
                    [
                        'per_hour' => 1500,
                        'per_two' => 2530,
                        'per_three' => 3800,
                        'per_two_plus' => 11132,
                        'per_three_plus' => 16720,
                        'five_ticket' => 10120,
                        'ten_ticket' => NULL,
                        'daypart' => 0,
                    ],  
                    [
                        'per_hour' => 1580,
                        'per_two' => 2670,
                        'per_three' => 4000,
                        'per_two_plus' => 11748,
                        'per_three_plus' => 17600,
                        'five_ticket' => 10680,
                        'ten_ticket' => NULL,
                        'daypart' => 0,
                    ],  
                    [
                        'per_hour' => 420,
                        'per_two' => 2400,
                        'per_three' => 3600,
                        'per_two_plus' => 2640,
                        'per_three_plus' => 3960,
                        'five_ticket' => 2400,
                        'ten_ticket' => NULL,
                        'daypart' => 0,
                    ],  
                    [
                        'per_hour' => 750,
                        'per_two' => 1200,
                        'per_three' => 1800,
                        'per_two_plus' => 5280,
                        'per_three_plus' => 7920,
                        'five_ticket' => 4800,
                        'ten_ticket' => NULL,
                        'daypart' => 0,
                    ],  
                    [
                        'per_hour' => 2500,
                        'per_two' => 4800,
                        'per_three' => 7200,
                        'per_two_plus' => 22000,
                        'per_three_plus' => 33000,
                        'five_ticket' => 4800,
                        'ten_ticket' => NULL,
                        'daypart' => 0,
                    ],  
                    [
                        'per_hour' => 2500,
                        'per_two' => 5000,
                        'per_three' => 7500,
                        'per_two_plus' => 22000,
                        'per_three_plus' => 33000,
                        'five_ticket' => 20000,
                        'ten_ticket' => NULL,
                        'daypart' => 0,
                    ],  
                    [
                        'per_hour' => 1100,
                        'per_two' => 6320,
                        'per_three' => 9500,
                        'per_two_plus' => 6952,
                        'per_three_plus' => 10450,
                        'five_ticket' => 6320,
                        'ten_ticket' => NULL,
                        'daypart' => 0,
                    ],  
                    [
                        'per_hour' => 1500,
                        'per_two' => 1580,
                        'per_three' => 2375,
                        'per_two_plus' => 6952,
                        'per_three_plus' => 10450,
                        'five_ticket' => 9600,
                        'ten_ticket' => NULL,
                        'daypart' => 0,
                    ],  
                    [
                        'per_hour' => 1250,
                        'per_two' => NULL,
                        'per_three' => NULL,
                        'per_two_plus' => NULL,
                        'per_three_plus' => NULL,
                        'five_ticket' => NULL,
                        'ten_ticket' => NULL,
                        'daypart' => 0,
                    ],  
        ]);
    }
}
